### ISSUE TITLE
Enhancements

### ISSUE THREAD

**Issue by Neema** [keremciu/sketch-use-fontawesome#1]
Awesome work so far 
here are my initial impressions after using the plugin for a day 
1. Is there a way to load FontAwesome via the web without having to have it installed?
   Might want to include it as a dependency in the readme.
2. Related to the above, how about being able to load up a custom font (or adding more than just FontAwesome). This is assuming you have the other font's json file. 
3. Add by Filter and Alias - but I'm sure this is already on your roadmap.
4. Set default text size? Not sure if this is useful...
5. Be able to add an icon without having to have a text layer selected. 

Happy to help - started doing some research to hopefully contribute!

**Comment by keremciu** [comment]
I'm so glad you like it. Thank you so much for your suggestions.

1- I didn't find a method to load a font. If you know that, it would be good. But yes, I have added it into readme.
1. I'm trying to that now, I will try to add material icon font and flat icon(not sure about it). But If I don't find to clear way, I think they will be separated plugins. Maybe I can do a SVG font parser, it would be a solution about that. Yea, we'll see that I need more research now :)
2. Yep, I'm trying to build a clear UI. Maybe I can try to add more combobox for each (font-awesome) category.
3. Yep, I need to research about it but its really good point. You know they have some classes "fa-spin", "fa-stack", I would like to use them in Sketch but I don't know how we can do it :)
4. Yep, it must be developed! :+1: I'll add an if condition for it, if you don't have a selected text layer, it will add a new text layer. Maybe only add a new text layer can be a good solution. :question: What do you think about it? Because now we're changing the selected layer to add an icon.

Thanks for suggestions again, they are so useful things :zap:

**Comment by keremciu** [comment]
Hey,

We've so good updates now! I'm building a new plugin for all icon fonts.
https://github.com/keremciu/sketch-iconfont

I've added these things to current and new plugin, I hope you like it :)
